// fields-by-type.ts

export interface Field {
  label: string;
  name: string;
  type?: string;
  required?: boolean;
  maxLength?: number;
  placeholder?: string;
}

export const fieldsByType: Record<string, Field[]> = {
  Lodging: [
    {
      label: 'ชื่อโรงแรม',
      name: 'lodgingName',
      maxLength: 80,
      required: true,
      placeholder: 'e.g. Hilton Sukhumvit Bangkok',
    },
    {
      label: 'ที่อยู่โรงแรม',
      name: 'lodgingAddress',
      required: true,
      placeholder: 'e.g. 11 Sukhumvit Rd, Bangkok',
    },
    {
      label: 'ชื่อผู้จอง',
      name: 'underName',
      maxLength: 80,
      required: true,
      placeholder: 'e.g. Puttinat Lertwech',
    },
    {
      label: 'วันที่ Check in',
      name: 'checkinDate',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-02-10 14:00',
    },
    {
      label: 'วันที่ Check out',
      name: 'checkoutDate',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-02-12 12:00',
    },
    {
      label: 'หมายเลขการจอง',
      name: 'bookingRef',
      placeholder: 'e.g. ABC12345',
    },
    {
      label: 'เบอร์ติดต่อ',
      name: 'contactTel',
      maxLength: 10,
      placeholder: 'e.g. 0812345678',
    },
    {
      label: 'Email ติดต่อ',
      name: 'contactEmail',
      type: 'email',
      maxLength: 80,
      placeholder: 'e.g. contact@email.com',
    },
    {
      label: 'ราคา',
      name: 'cost',
      type: 'number',
      required: true,
      placeholder: 'e.g. 3500',
    },
  ],

  Restaurant: [
    {
      label: 'ชื่อร้านอาหาร',
      name: 'restaurantName',
      maxLength: 80,
      required: true,
      placeholder: 'e.g. Savoey Restaurant',
    },
    {
      label: 'ที่อยู่ร้านอาหาร',
      name: 'restaurantAddress',
      required: true,
      placeholder: 'e.g. ICONSIAM, Bangkok',
    },
    {
      label: 'ชื่อผู้จอง',
      name: 'underName',
      maxLength: 80,
      required: true,
      placeholder: 'e.g. Puttinat Lertwech',
    },
    {
      label: 'วันที่จอง',
      name: 'reservationDate',
      type: 'date',
      required: true,
      placeholder: 'e.g. 2026-03-01',
    },
    {
      label: 'เวลาที่จอง',
      name: 'reservationTime',
      type: 'time',
      placeholder: 'e.g. 18:30',
    },
    {
      label: 'หมายเลขโต๊ะ',
      name: 'tableNo',
      placeholder: 'e.g. T12',
    },
    {
      label: 'หมายเลขคิว',
      name: 'queueNo',
      placeholder: 'e.g. Q25',
    },
    {
      label: 'จำนวนสมาชิก',
      name: 'partySize',
      type: 'number',
      placeholder: 'e.g. 4',
    },
    {
      label: 'หมายเลขการจอง',
      name: 'bookingRef',
      placeholder: 'e.g. REST9876',
    },
    {
      label: 'เบอร์ติดต่อ',
      name: 'contactTel',
      maxLength: 10,
      placeholder: 'e.g. 0812345678',
    },
    {
      label: 'Email ติดต่อ',
      name: 'contactEmail',
      type: 'email',
      maxLength: 80,
      placeholder: 'e.g. booking@email.com',
    },
    {
      label: 'ราคา',
      name: 'cost',
      type: 'number',
      required: true,
      placeholder: 'e.g. 2500',
    },
  ],

  Flight: [
    {
      label: 'สายการบิน',
      name: 'airline',
      maxLength: 20,
      required: true,
      placeholder: 'e.g. Thai Airways',
    },
    {
      label: 'หมายเลขเที่ยวบิน',
      name: 'flightNo',
      maxLength: 6,
      required: true,
      placeholder: 'e.g. TG102',
    },
    {
      label: 'เวลา Boarding',
      name: 'boardingTime',
      type: 'datetime-local',
      placeholder: 'e.g. 2026-04-01 09:30',
    },
    {
      label: 'Gate',
      name: 'gateNo',
      maxLength: 4,
      placeholder: 'e.g. A12',
    },
    {
      label: 'สนามบินต้นทาง',
      name: 'departureAirport',
      required: true,
      placeholder: 'e.g. BKK',
    },
    {
      label: 'เวลาออกเดินทาง',
      name: 'departureTime',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-04-01 10:30',
    },
    {
      label: 'สนามบินปลายทาง',
      name: 'arrivalAirport',
      required: true,
      placeholder: 'e.g. NRT',
    },
    {
      label: 'เวลาถึง',
      name: 'arrivalTime',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-04-01 18:00',
    },
    {
      label: 'ชั้นโดยสาร',
      name: 'flightClass',
      maxLength: 10,
      placeholder: 'e.g. Economy',
    },
    {
      label: 'หมายเลขการจอง',
      name: 'bookingRef',
      placeholder: 'e.g. FLT8899',
    },
    {
      label: 'เบอร์ติดต่อ',
      name: 'contactTel',
      maxLength: 10,
      placeholder: 'e.g. 0812345678',
    },
    {
      label: 'Email ติดต่อ',
      name: 'contactEmail',
      type: 'email',
      maxLength: 80,
      placeholder: 'e.g. flight@email.com',
    },
    {
      label: 'ราคา',
      name: 'cost',
      type: 'number',
      required: true,
      placeholder: 'e.g. 12000',
    },
  ],

  Train: [
    {
      label: 'หมายเลขขบวน',
      name: 'trainNo',
      required: true,
      placeholder: 'e.g. TR45',
    },
    {
      label: 'ชั้นโดยสาร',
      name: 'trainClass',
      required: true,
      placeholder: 'e.g. First Class',
    },
    {
      label: 'ประเภทที่นั่ง',
      name: 'seatClass',
      required: true,
      placeholder: 'e.g. Sleeper',
    },
    {
      label: 'หมายเลขที่นั่ง',
      name: 'seatNo',
      required: true,
      placeholder: 'e.g. 12A',
    },
    {
      label: 'ชื่อผู้โดยสาร',
      name: 'passengerName',
      maxLength: 80,
      required: true,
      placeholder: 'e.g. Puttinat Lertwech',
    },
    {
      label: 'สถานีต้นทาง',
      name: 'departureStation',
      required: true,
      placeholder: 'e.g. Hua Lamphong',
    },
    {
      label: 'เวลาออกเดินทาง',
      name: 'departureTime',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-05-01 07:00',
    },
    {
      label: 'สถานีปลายทาง',
      name: 'arrivalStation',
      required: true,
      placeholder: 'e.g. Chiang Mai',
    },
    {
      label: 'เวลาถึง',
      name: 'arrivalTime',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-05-01 18:00',
    },
    {
      label: 'หมายเลขการจอง',
      name: 'bookingRef',
      placeholder: 'e.g. TRN3344',
    },
    {
      label: 'เบอร์ติดต่อ',
      name: 'contactTel',
      maxLength: 10,
      placeholder: 'e.g. 0812345678',
    },
    {
      label: 'Email ติดต่อ',
      name: 'contactEmail',
      type: 'email',
      maxLength: 80,
      placeholder: 'e.g. train@email.com',
    },
    {
      label: 'ราคา',
      name: 'cost',
      type: 'number',
      required: true,
      placeholder: 'e.g. 1500',
    },
  ],

  Bus: [
    {
      label: 'ชื่อบริษัทรถ',
      name: 'transportCompany',
      required: true,
      placeholder: 'e.g. Nakhonchai Air',
    },
    {
      label: 'สถานีต้นทาง',
      name: 'departureStation',
      required: true,
      placeholder: 'e.g. Mochit',
    },
    {
      label: 'เวลาออกเดินทาง',
      name: 'departureTime',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-06-01 08:00',
    },
    {
      label: 'สถานีปลายทาง',
      name: 'arrivalStation',
      required: true,
      placeholder: 'e.g. Khon Kaen',
    },
    {
      label: 'ประเภทรถ',
      name: 'busClass',
      placeholder: 'e.g. VIP 24 seats',
    },
    {
      label: 'ชื่อผู้โดยสาร',
      name: 'passengerName',
      maxLength: 80,
      required: true,
      placeholder: 'e.g. Puttinat Lertwech',
    },
    {
      label: 'หมายเลขที่นั่ง',
      name: 'seatNo',
      required: true,
      placeholder: 'e.g. 5B',
    },
    {
      label: 'หมายเลขการจอง',
      name: 'bookingRef',
      placeholder: 'e.g. BUS5566',
    },
    {
      label: 'เบอร์ติดต่อ',
      name: 'contactTel',
      maxLength: 10,
      placeholder: 'e.g. 0812345678',
    },
    {
      label: 'Email ติดต่อ',
      name: 'contactEmail',
      type: 'email',
      maxLength: 80,
      placeholder: 'e.g. bus@email.com',
    },
    {
      label: 'ราคา',
      name: 'cost',
      type: 'number',
      required: true,
      placeholder: 'e.g. 900',
    },
  ],

  Ferry: [
    {
      label: 'ชื่อบริษัทเรือ',
      name: 'transportCompany',
      required: true,
      placeholder: 'e.g. Lomprayah',
    },
    {
      label: 'ชื่อผู้โดยสาร',
      name: 'passengerName',
      maxLength: 80,
      required: true,
      placeholder: 'e.g. Puttinat Lertwech',
    },
    {
      label: 'ท่าเรือต้นทาง',
      name: 'departurePort',
      required: true,
      placeholder: 'e.g. Chumphon Pier',
    },
    {
      label: 'เวลาเรือออก',
      name: 'departureTime',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-07-01 09:00',
    },
    {
      label: 'ท่าเรือปลายทาง',
      name: 'arrivalPort',
      required: true,
      placeholder: 'e.g. Koh Tao',
    },
    {
      label: 'เวลาถึง',
      name: 'arrivalTime',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-07-01 11:30',
    },
    {
      label: 'ประเภทตั๋ว',
      name: 'ticketType',
      required: true,
      placeholder: 'e.g. One-way',
    },
    {
      label: 'หมายเลขการจอง',
      name: 'bookingRef',
      placeholder: 'e.g. FRY7788',
    },
    {
      label: 'เบอร์ติดต่อ',
      name: 'contactTel',
      maxLength: 10,
      placeholder: 'e.g. 0812345678',
    },
    {
      label: 'Email ติดต่อ',
      name: 'contactEmail',
      type: 'email',
      maxLength: 80,
      placeholder: 'e.g. ferry@email.com',
    },
    {
      label: 'ราคา',
      name: 'cost',
      type: 'number',
      required: true,
      placeholder: 'e.g. 1200',
    },
  ],

  CarRental: [
    {
      label: 'ชื่อบริษัทเช่า',
      name: 'rentalCompany',
      required: true,
      placeholder: 'e.g. Avis',
    },
    {
      label: 'รุ่นรถ',
      name: 'carModel',
      required: true,
      placeholder: 'e.g. Toyota Corolla',
    },
    {
      label: 'หมายเลขทะเบียน',
      name: 'vrn',
      maxLength: 10,
      required: true,
      placeholder: 'e.g. 1กข1234',
    },
    {
      label: 'ชื่อผู้เช่า',
      name: 'renterName',
      maxLength: 80,
      required: true,
      placeholder: 'e.g. Puttinat Lertwech',
    },
    {
      label: 'สถานที่รับรถ',
      name: 'pickupLocation',
      required: true,
      placeholder: 'e.g. Suvarnabhumi Airport',
    },
    {
      label: 'เวลารับรถ',
      name: 'pickupTime',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-08-01 10:00',
    },
    {
      label: 'สถานที่คืนรถ',
      name: 'dropoffLocation',
      required: true,
      placeholder: 'e.g. Downtown Bangkok',
    },
    {
      label: 'เวลาคืนรถ',
      name: 'dropoffTime',
      type: 'datetime-local',
      required: true,
      placeholder: 'e.g. 2026-08-05 18:00',
    },
    {
      label: 'หมายเลขการจอง',
      name: 'bookingRef',
      placeholder: 'e.g. CAR9999',
    },
    {
      label: 'เบอร์ติดต่อ',
      name: 'contactTel',
      maxLength: 10,
      placeholder: 'e.g. 0812345678',
    },
    {
      label: 'Email ติดต่อ',
      name: 'contactEmail',
      type: 'email',
      maxLength: 80,
      placeholder: 'e.g. rental@email.com',
    },
    {
      label: 'ราคา',
      name: 'cost',
      type: 'number',
      required: true,
      placeholder: 'e.g. 5000',
    },
  ],
};
